### ISSUE TITLE
Password parameter type issue

### ISSUE THREAD

**Issue by kevinvan17** [aruba/arubaos-switch-api-python#2]
Password in sampledata/data.yaml has to be defined as string , the original example will cause switch returns Bad Request 400 error. 
user: admin
password: admin   ---> Looks like admin has to be replaced as "admin" so a correct Post request can be generated by Request Module and interpreted by switch

**Comment by rajani-abraham** [comment]
Can you paste teh error message you getting? It should work without "".

**Comment by rajani-abraham** [comment]
Please checkout this video how the data.yaml used for password.  https://www.youtube.com/watch?v=SPKTTL8bsRY
